on: [push]

jobs:
  build-secure-and-push:
    runs-on: ubuntu-latest
    steps:
    env:
      DOCKER_CONTENT_TRUST: 1
    - uses: actions/checkout@master

    - run: docker build . -t registry.aves-it.nl/automx/automx2:${{ github.sha }}
      
    - uses: Azure/container-scan@v0
      with:
        image-name: registry.aves-it.nl/automx/automx2:${{ github.sha }}
    
    - uses: Azure/docker-login@v1
      with:
        login-server: registry.aves-it.nl
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: docker push registry.aves-it.nl/automx/automx2:${{ github.sha }}
