on:
  push:
    paths:
    - 'docker/**'
    - '.github/workflows/*private.yml'
  schedule:
    - cron: '0 2 1/14 * *'
name: private-build-scan-and-push
jobs:
  build-scan-and-push-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - run: docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` 
                        --build-arg VCS_REF=${{ github.sha }} 
                        --tag registry.aves-it.nl/automx/automx2:${{ github.sha }} 
                        --tag registry.aves-it.nl/automx/automx2:latest 
                        docker/
      
    - uses: Azure/container-scan@v0
      with:
        image-name: registry.aves-it.nl/automx/automx2:${{ github.sha }}
    
    - uses: Azure/docker-login@v1
      with:
        login-server: registry.aves-it.nl
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: docker push registry.aves-it.nl/automx/automx2

  build-scan-and-push-branch:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - run: docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` 
                        --build-arg VCS_REF=${{ github.sha }} 
                        --tag registry.aves-it.nl/automx/automx2:${{ github.sha }} 
                        --tag registry.aves-it.nl/automx/automx2:${GITHUB_REF##*/} 
                        docker/

    - uses: Azure/container-scan@v0
      with:
        image-name: registry.aves-it.nl/automx/automx2:${{ github.sha }}
   
    - uses: Azure/docker-login@v1
      with:
        login-server: registry.aves-it.nl
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
   
    - run: docker push registry.aves-it.nl/automx/automx2

